#ifndef TEAMS_H
#define TEAMS_H

#include <string>
#include <vector>

static const std::vector<std::string> teams = // NOLINT(cert-err58-cpp)
{
    "KRC Genk",
    "Beerschot AC",
    "SV Zulte-Waregem",
    "Sporting Lokeren",
    "KSV Cercle Brugge",
    "RSC Anderlecht",
    "KAA Gent",
    "RAEC Mons",
    "FCV Dender EH",
    "Standard de Liège",
    "KV Mechelen",
    "Club Brugge KV",
    "KSV Roeselare",
    "KV Kortrijk",
    "Tubize",
    "Royal Excel Mouscron",
    "KVC Westerlo",
    "Sporting Charleroi",
    "Sint-Truidense VV",
    "Lierse SK",
    "KAS Eupen",
    "Oud-Heverlee Leuven",
    "Waasland-Beveren",
    "KV Oostende",
    "Royal Excel Mouscron",
    "Manchester United",
    "Newcastle United",
    "Arsenal",
    "West Bromwich Albion",
    "Sunderland",
    "Liverpool",
    "West Ham United",
    "Wigan Athletic",
    "Aston Villa",
    "Manchester City",
    "Everton",
    "Blackburn Rovers",
    "Middlesbrough",
    "Tottenham Hotspur",
    "Bolton Wanderers",
    "Stoke City",
    "Hull City",
    "Fulham",
    "Chelsea",
    "Portsmouth",
    "Birmingham City",
    "Wolverhampton Wanderers",
    "Burnley",
    "Blackpool",
    "Swansea City",
    "Queens Park Rangers",
    "Norwich City",
    "Southampton",
    "Reading",
    "Crystal Palace",
    "Cardiff City",
    "Leicester City",
    "Bournemouth",
    "Watford",
    "AJ Auxerre",
    "FC Nantes",
    "Girondins de Bordeaux",
    "SM Caen",
    "Le Havre AC",
    "OGC Nice",
    "Le Mans FC",
    "FC Lorient",
    "Olympique Lyonnais",
    "Toulouse FC",
    "AS Monaco",
    "Paris Saint-Germain",
    "AS Nancy-Lorraine",
    "LOSC Lille",
    "Stade Rennais FC",
    "Olympique de Marseille",
    "FC Sochaux-Montbéliard",
    "Grenoble Foot ",
    "Valenciennes FC",
    "AS Saint-Étienne",
    "RC Lens",
    "Montpellier Hérault SC",
    "US Boulogne Cote D'Opale",
    "AC Arles-Avignon",
    "Stade Brestois ",
    "AC Ajaccio",
    "Évian Thonon Gaillard FC",
    "Dijon FCO",
    "Stade de Reims",
    "SC Bastia",
    "ES Troyes AC",
    "En Avant de Guingamp",
    "FC Metz",
    "Angers SCO",
    "GFC Ajaccio",
    "FC Bayern Munich",
    "Hamburger SV",
    "Bayer Leverkusen",
    "Borussia Dortmund",
    "FC Schalke ",
    "Hannover ",
    "VfL Wolfsburg",
    "1. FC Köln",
    "Eintracht Frankfurt",
    "Hertha BSC Berlin",
    "DSC Arminia Bielefeld",
    "SV Werder Bremen",
    "FC Energie Cottbus",
    "TSG Hoffenheim",
    "Borussia Mönchengladbach",
    "VfB Stuttgart",
    "Karlsruher SC",
    "VfL Bochum",
    "SC Freiburg",
    "1. FC Nürnberg",
    "1. FSV Mainz ",
    "1. FC Kaiserslautern",
    "FC St. Pauli",
    "FC Augsburg",
    "Fortuna Düsseldorf",
    "SpVgg Greuther Fürth",
    "Eintracht Braunschweig",
    "SC Paderborn ",
    "FC Ingolstadt ",
    "SV Darmstadt ",
    "Atalanta",
    "Siena",
    "Cagliari",
    "Lazio",
    "Catania",
    "Genoa",
    "Chievo Verona",
    "Reggio Calabria",
    "Fiorentina",
    "Juventus",
    "Milan",
    "Bologna",
    "Roma",
    "Napoli",
    "Sampdoria",
    "Inter",
    "Torino",
    "Lecce",
    "Udinese",
    "Palermo",
    "Bari",
    "Livorno",
    "Parma",
    "Cesena",
    "Brescia",
    "Novara",
    "Pescara",
    "Hellas Verona",
    "Sassuolo",
    "Empoli",
    "Frosinone",
    "Carpi",
    "Vitesse",
    "FC Groningen",
    "Roda JC Kerkrade",
    "FC Twente",
    "Willem II",
    "Ajax",
    "N.E.C.",
    "De Graafschap",
    "FC Utrecht",
    "PSV",
    "Heracles Almelo",
    "Feyenoord",
    "Sparta Rotterdam",
    "ADO Den Haag",
    "FC Volendam",
    "SC Heerenveen",
    "AZ",
    "NAC Breda",
    "RKC Waalwijk",
    "VVV-Venlo",
    "Excelsior",
    "PEC Zwolle",
    "SC Cambuur",
    "Go Ahead Eagles",
    "FC Dordrecht",
    "Wisla Kraków",
    "Polonia Bytom",
    "Polonia Bytom",
    "Ruch Chorzów",
    "Legia Warszawa",
    "P. Warszawa",
    "Slask Wroclaw",
    "Lechia Gdansk",
    "Widzew Lódz",
    "Odra Wodzislaw",
    "Lech Poznan",
    "GKS Belchatów",
    "Arka Gdynia",
    "Jagiellonia Bialystok",
    "Piast Gliwice",
    "Cracovia",
    "Korona Kielce",
    "Zaglebie Lubin",
    "Widzew Lódz",
    "Podbeskidzie Bielsko-Biala",
    "Pogon Szczecin",
    "Zawisza Bydgoszcz",
    "Górnik Leczna",
    "Termalica Bruk-Bet Nieciecza",
    "FC Porto",
    "CF Os Belenenses",
    "Sporting CP",
    "Trofense",
    "Vitória Guimarães",
    "Vitória Setúbal",
    "FC Paços de Ferreira",
    "SC Braga",
    "Amadora",
    "Académica de Coimbra",
    "Rio Ave FC",
    "SL Benfica",
    "Leixões SC",
    "CD Nacional",
    "Naval 1° de Maio",
    "CS Marítimo",
    "União de Leiria, SAD",
    "S.C. Olhanense",
    "Portimonense",
    "SC Beira Mar",
    "Feirense",
    "Gil Vicente FC",
    "Moreirense FC",
    "Estoril Praia",
    "FC Arouca",
    "FC Penafiel",
    "Boavista FC",
    "Uniao da Madeira",
    "Tondela",
    "Falkirk",
    "Rangers",
    "Heart of Midlothian",
    "Motherwell",
    "Kilmarnock",
    "Hibernian",
    "Aberdeen",
    "Inverness Caledonian Thistle",
    "Celtic",
    "St. Mirren",
    "Hamilton Academical FC",
    "Dundee United",
    "St. Johnstone FC",
    "Dunfermline Athletic",
    "Dundee FC",
    "Ross County FC",
    "Partick Thistle F.C.",
    "Valencia CF",
    "RCD Mallorca",
    "CA Osasuna",
    "Villarreal CF",
    "RC Deportivo de La Coruña",
    "Real Madrid CF",
    "CD Numancia",
    "FC Barcelona",
    "Racing Santander",
    "Sevilla FC",
    "Real Sporting de Gijón",
    "Getafe CF",
    "Real Betis Balompié",
    "RC Recreativo",
    "RCD Espanyol",
    "Real Valladolid",
    "Athletic Club de Bilbao",
    "UD Almería",
    "Atlético Madrid",
    "Málaga CF",
    "Xerez Club Deportivo",
    "Real Zaragoza",
    "CD Tenerife",
    "Hércules Club de Fútbol",
    "Levante UD",
    "Real Sociedad",
    "Granada CF",
    "Rayo Vallecano",
    "RC Celta de Vigo",
    "Elche CF",
    "SD Eibar",
    "Córdoba CF",
    "UD Las Palmas",
    "Grasshopper Club Zürich",
    "AC Bellinzona",
    "BSC Young Boys",
    "FC Basel",
    "FC Aarau",
    "FC Sion",
    "FC Luzern",
    "FC Vaduz",
    "Neuchâtel Xamax",
    "FC Zürich",
    "FC St. Gallen",
    "FC Thun",
    "Servette FC",
    "FC Lausanne-Sports",
    "Lugano"
};

#endif // TEAMS_H
